### ISSUE TITLE
Unable to Package for Titanium 6.0.0

### ISSUE THREAD

**Issue by GeorgeWebDesign** [mdescher/titanium-mediacontrols#1]
Hi

I love this module and have been using it for a couple of years.

I am having issues packaging up the module for 6.0.0.

these 2 errors:

1 - 
[ERROR] :  [xcode-sim] The following build commands failed:
[ERROR] :  [xcode-sim] 	CompileC build/MediaControls.build/Release-iphonesimulator/MediaControls.build/Objects-normal/i386/DeCodewaveTiMediacontrolsViewProxy.o Classes/DeCodewaveTiMediacontrolsViewProxy.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[ERROR] :  [xcode-sim] 	CompileC build/MediaControls.build/Release-iphonesimulator/MediaControls.build/Objects-normal/i386/DeCodewaveTiMediacontrolsModule.o Classes/DeCodewaveTiMediacontrolsModule.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[ERROR] :  [xcode-sim] (2 failures)

2 -
Launching build and packaging failed
Build failed. Unable to locate generated zip file at /Users/garygeorge/Desktop/titanium-mediacontrols-master/de.codewave.ti.mediacontrols-iphone-4.3.zip

Do you have any clue as how to package it for 6.0.0

thank you
Gary

**Comment by mdescher** [comment]
Problem was solved using Ti 6.0.1 instead of Ti 6.0.0.
